server:
  port: 8887

#禁用Thymeleaf模板缓存
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/db_community
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# 开启mybatis驼峰标识
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#配置pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: countSql

# 自定义参数配置
github:
  client_id: b3118b6cffce13fd5b90
  client_secret: 9f1aecb40972c18e89eab70f3612af47d3aa2272
  redirect_uri: http://localhost:8887/callback