server:
  port: 8887
#禁用Thymeleaf模板缓存
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/db_community
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# 开启mybatis驼峰标识
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sjl.community.mapper

# Github登录需要的参数
github:
  client_id: aeb0d5116950de9541ab
  client_secret: ff77def3f0aecb61c0544eb6296faf213cb13c11
  redirect_uri: http://localhost:8887/callback