server:
  port: 8887

#禁用Thymeleaf模板缓存
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/db_community
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
# 开启mybatis驼峰标识
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#配置pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: countSql

# 自定义参数配置
github:
  client_id: b3118b6cffce13fd5b90
  client_secret: 8563567bd5aaf80204420cf61002303fdce4f431
  redirect_uri: http://localhost:8887/callback
  token_uri: https://github.com/login/oauth/access_token
  user_uri: https://api.github.com/user?access_token=