server:
  port: 8887
#禁用Thymeleaf模板缓存
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://cdb-ourugxty.cd.tencentcdb.com:10110/db_community
    username: root
    password: 0624songjilong
    driver-class-name: com.mysql.jdbc.Driver

# 开启mybatis驼峰标识
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sjl.community.mapper

# Github登录需要的参数
github:
  client-id: aeb0d5116950de9541ab
  client-secret: ff77def3f0aecb61c0544eb6296faf213cb13c11
  redirect-uri: http://121.36.34.135/callback

# 阿里云图片上传需要的参数
aliyun:
  endpoint: http://oss-cn-hangzhou.aliyuncs.com
  accessKeyId: LTAI4FcQmixvAcadvrWzjFWX
  accessKeySecret: Yo6pIhpahRINc1otp72Q2RtQIcZLxH
  bucketName: beetle-community
  firstKey: my-first-key

# 日志配置
logging:
  level: info
  level.com.sjl.community.mapper: debug
  file:
    name: log/community.log
    max-size: 200MB
    max-history: 30