server:
  port: 8887
#禁用Thymeleaf模板缓存
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/db_community
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# 开启mybatis驼峰标识
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sjl.community.mapper

# Github登录需要的参数
github:
  client-id: e15804a8ca66dfd118c3
  client-secret: 4f289ae5ab7650a5e88a3d8ded6e5a4fb4a89791
  redirect-uri: http://localhost:8887/callback

# QQ登录需要的参数
qq:
  client_id: 101852195
  client_secret: 12faca5851ca79d3af64352a8664cf32
  redirect_uri: http://127.0.0.1:8887/qqLogin

# 阿里云图片上传需要的参数
aliyun:
  endpoint:
  accessKeyId:
  accessKeySecret:
  bucketName:

# 日志配置
logging:
  level: info
  level.com.sjl.community.mapper: debug
  file:
    name: log/community.log
    max-size: 200MB
    max-history: 30